# --------------------------------------------------
# Site settings
title: Velllum Interface Framework
description: Clean Modular CSS Interface Framework for Responsive Web Apps
owner: http://github.com/velllum
repo: velllum-ui
branch: gh-pages

# --------------------------------------------------
# Site imagery
favicon: /ui/img/graph/favicon.png
avatar: /ui/img/graph/avatar.png
poster: /ui/img/graph/poster.jpg

# --------------------------------------------------
# the subpath of your site, e.g. /blog
baseurl: ""
# css container
namespace: velllum

# --------------------------------------------------
# Build settings
sass:
  style: compressed
  sass_dir: ui/_sass

collections:
  pages:
    output: true
    permalink: /:path/
  documentation:
    output: true
    permalink: /documentation/:path/
  specifications:
    output: true
    permalink: /documentation/:path/
  examples:
    output: true
    permalink: /examples/:path/

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "pages"
-
  scope:
    path: ""
    type: "documentation"
  values:
    layout: "documentation"
-
  scope:
    path: ""
    type: "examples"
  values:
    layout: "examples"
-
  scope:
    path: ""
    type: "specifications"
  values:
    layout: "specifications"




