# --------------------------------------------------
# Site settings

title: Velllum Interface Framework
description: Clean Modular CSS Interface Framework for Responsive Web Apps
robots: false

# --------------------------------------------------
# Site imagery

favicon: /favicon.ico
avatar: /ui/img/graph/avatar.png
poster: /ui/img/graph/poster.png

# --------------------------------------------------
# the subpath of your site, e.g. /blog

url: "https://ui.velllum.com"
baseurl: "/"

# --------------------------------------------------
# Includes

typekit: false
googlefonts: false
bootstrap: true
jqueryui: true
svgicons: true
inliner: false

# --------------------------------------------------
# Build settings

sass:
  style: compressed
  sass_dir: _includes

collections:
  docs:
    output: true
    permalink: /docs/:path/
  pages:
    output: true
    permalink: /:path/

defaults:
-
  scope:
    path: ""
    type: "docs"
  values:
    layout: "doc"
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"



